name: Test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod 777 $(php-config --extension-dir)
      - run: ./bin/detect
      - run: ./bin/compile $PWD $PWD
      - run: ./bin/release
